read graph data from graph directly
earthcube/earthcube_utilities pull request #141
Opened 2023-11-20 18:31 UTC by ylyangtw

2023-12-18 20:43 UTC, valentinedwv approved these changes

2023-12-19 18:27 UTC, valentinedwv requested changes
Running against the summary and the graph are two different things, so let's have two different spraql queries.

And maybe just have the option to say summary graph, or quads graph.

2023-12-19 19:49 UTC, ylyangtw commented
> Running against the summary and the graph are two different things, so let's have two different spraql queries.
> 
> And maybe just have the option to say summary graph, or quads graph.

Agreed! I just committed the changes -- separating the sparql queries. I also added comments that the endpoint for this report should be based on summary. @valentinedwv

2023-12-20 18:16 UTC, valentinedwv approved these changes

2023-12-20 19:38 UTC, merged