Dev mb, last summarization steps w/graph class for blaze v fuseki, more checks&final upload
earthcube/earthcube_utilities pull request #23
Opened 2023-02-15 22:31 UTC by MBcode

last summarization steps w/graph class for blaze v fuseki, more checks&final upload

it works w/the insert by nq2blaze.sh but getting 404 on good url for insert method

2023-02-16 21:35 UTC, MBcode commented
I mentioned the docs update, in a docs [issue](https://github.com/earthcube/geocodes/issues/16) comment

2023-02-17 00:51 UTC, valentinedwv requested changes
Update the documentation to tell me what env varaiables i'm supposed to be using.
Perhaps use arparse on getrepo, so that we don't have to use them.

2023-02-17 00:51 UTC, valentinedwv commented on summarize/README.md
> +* install dependinces
hints. maybe say how to install fuskei?

2023-02-17 00:51 UTC, valentinedwv commented on summarize/README.md
> +3. run> `repo2summary.sh repo`
Do I need to set any env variables. how would i Know unless I read the code

2023-02-17 00:51 UTC, valentinedwv commented on summarize/src/fnq.py
> +        ftsp=os.getenv('tmp_summary_port')
???

2023-02-17 00:51 UTC, valentinedwv commented on summarize/src/get_repo.py
> +    wget_oss_repo(repo=repo,path="gleaner/milled",s3address=default_s3address)
wget?

2023-02-17 00:51 UTC, valentinedwv commented on summarize/src/get_repo.py
> +    s3=os.getenv("ECU_S3ADDRESS")
Needs to be in doco

2023-02-17 15:17 UTC, MBcode commented on summarize/README.md
> +* install dependinces
get_repo.py reads ECU_S3ADDRESS and an env var, but will add argparse as well
Once you switched to blaze (that is already installed) we don't use fuseki anymore

2023-02-17 16:09 UTC, MBcode commented on summarize/README.md
> +* install dependinces
updated dependency section, and readme already asks for ECU_S3ADDRESS if you want a different one;  the help for get_repo.py will also allow overriding that

2023-02-17 16:11 UTC, MBcode commented on summarize/src/fnq.py
> +        ftsp=os.getenv('tmp_summary_port')
i'll close out this outdated comment too; as no fuseki being used now the fnq.py fuseki started is only around as a util, for those that want quick local access

2023-02-17 16:12 UTC, MBcode commented on summarize/src/get_repo.py
> +    wget_oss_repo(repo=repo,path="gleaner/milled",s3address=default_s3address)
if this isn't part of stock alpine in the container, I can move to requesting them

2023-02-17 16:13 UTC, MBcode commented on summarize/src/get_repo.py
> +    s3=os.getenv("ECU_S3ADDRESS")
another outdated comment/but think env var has been in the [docs](https://github.com/earthcube/earthcube_utilities/blob/dev_mb/summarize/README.md) for awhile now

2023-02-17 16:14 UTC, MBcode commented on summarize/README.md
> +3. run> `repo2summary.sh repo`
old comment/bc in [doc](https://github.com/earthcube/earthcube_utilities/blob/dev_mb/summarize/README.md)s for a bit

2023-02-17 16:25 UTC, MBcode commented on summarize/src/get_repo.py
> +    wget_oss_repo(repo=repo,path="gleaner/milled",s3address=default_s3address)
changed to request, and updated doc

2023-02-17 16:31 UTC, MBcode commented on summarize/src/get_repo.py
> +    wget_oss_repo(repo=repo,path="gleaner/milled",s3address=default_s3address)
was verified, put requests back in requirements.txt should be ok, but getting:
'does not appear to be a Python project: no pyproject.toml' again

2023-02-17 16:41 UTC, valentinedwv approved these changes
I'd say remove dead code, but works so approved

2023-02-17 16:49 UTC, MBcode commented on summarize/src/get_repo.py
> +    wget_oss_repo(repo=repo,path="gleaner/milled",s3address=default_s3address)
will get commented out of workflow

2023-02-18 20:34 UTC, merged