55 method to provide summary of indentifier metadata in s3
earthcube/earthcube_utilities pull request #64
Opened 2023-04-19 17:59 UTC by ylyangtw

Generated txt file:
![image](https://user-images.githubusercontent.com/63822845/233160470-c3d4d979-4744-4fe6-a3f6-42144b73305b.png)

Json file uploaded to s3 for each repository:
![image](https://user-images.githubusercontent.com/63822845/233160687-d20236bf-3fb2-4f32-94cb-53575f043892.png)

2023-04-19 22:26 UTC, valentinedwv requested changes

2023-04-19 22:26 UTC, valentinedwv commented on earthcube_utilities/src/ec/summarize_identifier_metadata.py
> +        return 'Matchedpath does not exist'
Can we just use None? or Not Applicable

2023-04-19 22:26 UTC, valentinedwv commented on earthcube_utilities/src/ec/summarize_identifier_metadata.py
> +        o_list = list(map(lambda f: {'Identifiertype': f.metadata['X-Amz-Meta-Identifiertype'],
Try using[ get('name')](https://realpython.com/python-dicts/#dgetkey-default)

f.metadata.get('X-Amz-Meta-Identifiertype')
f.metadata.get('X-Amz-Meta-Matchedpath')
f.metadata.get('X-Amz-Meta-Uniqueid')

this would return None and not an exception if it is not present, so checked path becomes unneeded.

2023-04-19 22:26 UTC, valentinedwv commented on earthcube_utilities/src/ec/summarize_identifier_metadata.py
> +                o = json.loads(o.to_json(orient = 'index'))
lets make both dumps csv (see [sitemap](https://github.com/earthcube/earthcube_utilities/blob/eeabc6c5d7a7c532011de70824e76a914b607d43/earthcube_utilities/src/ec/sitemap/sitemap.py#L99)).
"source", "IdentifierType", "Matchedpath", "UniqueCount"

2023-04-20 14:40 UTC, valentinedwv commented on earthcube_utilities/src/ec/summarize_identifier_metadata.py
> +                o = json.loads(o.to_json(orient = 'index'))
what happens if you change the orientation to records
orient='records'

2023-04-20 14:42 UTC, valentinedwv commented on earthcube_utilities/src/ec/summarize_identifier_metadata.py
> +                o = json.loads(o.to_json(orient = 'index'))
add --json, and convert the csv output to json.

2023-04-20 14:44 UTC, valentinedwv commented
Also,

-  add to [project.scripts] in earthcube_utilites/pyproject.toml
- documentation

2023-04-20 14:50 UTC, valentinedwv commented on earthcube_utilities/src/ec/summarize_identifier_metadata.py
> +                        dest='output', help='dump to file')
add a --source argument (aka repo)...
if one or more source is pass, just use those repository names

which probably means it's best to make a list of just the 'Name' fields using map(lambda r: r.get('Name'), sources) so you can get rid of the repo.get('Name) in the 'for repo in source loop'

2023-04-20 15:12 UTC, valentinedwv commented on earthcube_utilities/src/ec/summarize_identifier_metadata.py
> +            o = df.groupby(['Identifiertype', 'Matchedpath']).count()
good practice says name it what it is.
indentifier_stats

2023-04-20 15:14 UTC, valentinedwv commented on earthcube_utilities/src/ec/summarize_identifier_metadata.py
> +                o = json.loads(o.to_json(orient = 'index'))
avoid reusing the variable name that you put the identifier_stats into.
You lose the ability when debugging to see what was transformed when you redefine 
an important data structure.

2023-04-20 15:52 UTC, valentinedwv commented
ignore the notebook_proxy failing... it's fixed. you can pull change from the dev branch.

2023-04-20 17:50 UTC, valentinedwv commented
After grouped,  can you add a column, 'example' with an array of (1 to 5) Uniqueid's from the original df?
if it's only one to five return all of them, if it's more, return first 5.

It would help make any debugging of issues easier

2023-04-21 13:33 UTC, ylyangtw commented on earthcube_utilities/src/ec/summarize_identifier_metadata.py
> +        o_list = list(map(lambda f: {'Identifiertype': f.metadata['X-Amz-Meta-Identifiertype'],
cool! it works

2023-04-21 14:36 UTC, ylyangtw commented on earthcube_utilities/src/ec/summarize_identifier_metadata.py
> +        try:
Thanks much!

2023-04-21 18:32 UTC, ylyangtw commented on earthcube_utilities/src/ec/summarize_identifier_metadata.py
> +                        dest='output', help='dump to file')
good suggestion!

2023-04-21 20:25 UTC, ylyangtw commented
> Also,
> 
> * add to [project.scripts] in earthcube_utilites/pyproject.toml
> * documentation

Made this change under branch 'docs'.

2023-04-21 21:21 UTC, valentinedwv commented on earthcube_utilities/src/ec/summarize_identifier_metadata.py
> +    repos = args.source
We only need the name, so I think this can be simplified>
if args.source:
   sources = args.source
else:
  sources = getSitemapSourcesFromGleaner(args.cfgfile)
    sources = list(filter(lambda source: source.get('active'), sources))
    sources = list(map(lambda r: r.get('name'), sources))
 
and get rid of the checking in the loop

2023-04-21 21:22 UTC, valentinedwv commented on earthcube_utilities/src/ec/summarize_identifier_metadata.py
> +                .agg({'Uniqueid': 'count', 'Example':lambda x: x.iloc[0:5].tolist()}).reset_index()
slick

2023-04-21 21:30 UTC, valentinedwv commented on earthcube_utilities/src/ec/summarize_identifier_metadata.py
> +    repos = args.source
That way we can ask to run a not active source,
same thing happens in gleaner, except it sets it to active

2023-04-21 21:35 UTC, valentinedwv commented on earthcube_utilities/src/ec/summarize_identifier_metadata.py
> +                        help='gleaner config file', default='gleaner')
Cannot be a default.. otherwise it tries to load the file that does not exist

2023-04-21 21:51 UTC, valentinedwv commented
I just made the changes... and merged with dev so hopefully we get all green ;)
love how you used agg to get the sha's in there.

2023-04-21 22:00 UTC, valentinedwv approved these changes

2023-04-21 22:30 UTC, ylyangtw commented on earthcube_utilities/src/ec/summarize_identifier_metadata.py
> +        objs = map(lambda f: s3Minio.s3client.stat_object(f.bucket_name, f.object_name), jsonlds)
Just realized I haven't worked in this yet. But think it would be nice to resolve them.
Created another 2 issues so that way we don't forget.
https://github.com/earthcube/earthcube_utilities/issues/69
https://github.com/earthcube/earthcube_utilities/issues/70

2023-04-21 22:32 UTC, ylyangtw commented
> I just made the changes... and merged with dev so hopefully we get all green ;) love how you used agg to get the sha's in there.

Thanks much! :D
Tried a few different approaches and found this one works the best

2023-04-21 22:32 UTC, merged